[files]
extend-exclude = [".git", "minq", "docs/ibcdfo.bib"]
ignore-hidden = false

[default]
check-filename = true
check-file = true
binary = false
locale = "en"
unicode = true

[default.extend-words]
Nd = "Nd"
gam = "gam"
