# ----- IBCDFO FULL TESTING OF INSTALLED PACKAGE WITHOUT COVERAGE
name: Test IBCDFO Python Package
env:
  GH_ACTIONS_PATH: ${{ github.workspace }}/.github/workflows
  IBCDFO_PKG:      ${{ github.workspace }}/ibcdfo_pypkg
  BENDFO_PY_PATH:  ${{ github.workspace }}/BenDFO/py
  MINQ5_PY_PATH:   ${{ github.workspace }}/minq/py/minq5
on:
  # This action is used only to run a significant but smallish set of test
  # setups on feature branches.
  #
  # More thorough testing is done on main with the release action as part of
  # creating and verifying potential release candidate distributions.
  pull_request:
    branches: [main]

jobs:
  test_ibcdfo:
    strategy:
      # python-versions must be maintained consistent with associated setup.py
      # and tox.ini configuration.
      #
      # TODO: Strange failures on macos-15-intel prevent its use (Issue 235).
      # This means that this action is **not** running any mac tests using Intel
      # chips.
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-14, macos-15]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    runs-on: ${{ matrix.os }}
    steps:
    # -- General Setup Steps
    # This action requires minq
    - name: Checkout IBCDFO repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Checkout BenDFO repository
      uses: actions/checkout@v4
      with:
        repository: POptUS/BenDFO
        path: BenDFO
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Python with tox
      run: $GH_ACTIONS_PATH/setup_tox_github_action.sh ${{ runner.os }}

    # -- Run test suite through installation
    # The tox task downloads dfo.dat automatically
    - name: Test IBCDFO Python package
      run: |
        export PYTHONPATH=$BENDFO_PY_PATH:$MINQ5_PY_PATH
        echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV
        pushd $IBCDFO_PKG
        tox -r -e nocoverage
        popd
