name: Test Oldest Versions
env:
  GH_ACTIONS_PATH: ${{ github.workspace }}/.github/workflows
  IBCDFO_PKG:      ${{ github.workspace }}/ibcdfo_pypkg
  BENDFO_PY_PATH:  ${{ github.workspace }}/BenDFO/py
  MINQ5_PY_PATH:   ${{ github.workspace }}/minq/py/minq5
on:
  # TODO: Make this manual trigger only?
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_supported:
    strategy:
      # python-versions must be maintained consistent with associated
      # pyproject.toml and tox.ini configuration.
      #
      # TODO: Strange failures on macos-15-intel prevent its use (Issue 235).
      # This means that this action is **not** running any mac tests using Intel
      # chips.
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-14, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
    # This action requires minq
    - name: Checkout IBCDFO repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Checkout BenDFO repository
      uses: actions/checkout@v4
      with:
        repository: POptUS/BenDFO
        path: BenDFO
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: 3.10
    - name: Setup Python with tox
      run: $GH_ACTIONS_PATH/setup_tox_github_action.sh ${{ runner.os }}

    # The tox task downloads dfo.dat automatically
    - name: Run test suite
      run: |
        export PYTHONPATH=$BENDFO_PY_PATH:$MINQ5_PY_PATH
        echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV
        pushd $IBCDFO_PKG
        tox -r -e oldest
        popd
